openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Students 
  license:
    name: MIT
servers:
  - url: http://localhost:2000
paths:
  /students:
    get:
      summary: List of all students
      operationId: listStudents
      tags: 
        - Student
      responses:
        '200':
          description: Array of students
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/ResponseStudents'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a student
      operationId: createStudent
      tags:
        - Student
      requestBody:
        description: create a student
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudents'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /students/{studentId}:
    get:
      summary: Info for a specific student
      operationId: showStudentById
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: The id of the student to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudent'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a specific student
      operationId: updateStudentByID
      tags:
        - Student
      requestBody:
        description: update student information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      parameters:
      - name: studentId
        in: path
        required: true
        description: The id of the user to retrieve
        schema:
          type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudent'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a specific student
      operationId: deleteStudentByID
      tags: 
        - Student
      parameters: 
      - name: studentId
        in: path
        required: true
        description: Deletes the student
        schema:
          type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudent'
        '204':
          description: Valid request but there is nothing to delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Student:
      properties:
        name:
          type: string
        email:
          type: string
        address:
          properties:
            street:
              type: string
            city:
              type: string
            zipcode:
              type: string
    ResponseStudent:
      allOf:
      - $ref: '#/components/schemas/Student'
      - properties:
          id:
            type: integer
          _id:
            type: string
            format: uuid
    ResponseStudents:
      type: array
      items:
        $ref: '#/components/schemas/ResponseStudent'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    